webtalk_init -webtalk_dir C:/Users/Chuong/Documents/Verilog/Control/Control.sim/sim_1/behav/xsim.dir/sim_Control_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon May 16 00:19:36 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2015.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1412921" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211184220_0_0_701" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4e8d8dee-b376-4264-aab8-bb78e2d020b4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3f2d88b819fc4bc281572bc1131f9b12" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Athlon(tm) II X4 630 Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2793 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.31_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "19976_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2478695213 -regid "211184220_0_0_701" -xml C:/Users/Chuong/Documents/Verilog/Control/Control.sim/sim_1/behav/xsim.dir/sim_Control_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Chuong/Documents/Verilog/Control/Control.sim/sim_1/behav/xsim.dir/sim_Control_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Chuong/Documents/Verilog/Control/Control.sim/sim_1/behav/xsim.dir/sim_Control_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
